### ISSUE TITLE
Export properties type for each component

### ISSUE THREAD

**Issue by mmrath** [kobaltedev/kobalte#106]
**Is your feature request related to a problem? Please describe.**
When creating wrapper component it would be handy to have the type of properties of a component. Currently there is options but that is not the full list of properties of the component

**Describe the solution you'd like**
I am thinking that for each polymorphicComponent we export the corresponding props. for example for AccordionHeader, something like
```
export type AccordionHeaderProps = ....
```

**Describe alternatives you've considered**
the types can be created by consumer but it does not look great

**Additional context**
This will be specifically useful to create wrappers

**Comment by fabien-ml** [comment]
Hi, thanks for reporting the issue.

If I understand correctly, you want something like this:

```ts
// Kobalte custom options
export interface AccordionHeaderOptions {}

// Kobalte custom options + the native HTML `h3` props
export type AccordionHeaderProps = ...
```

**Comment by mmrath** [comment]
Thank you. That is correct.

**Comment by mmrath** [comment]
Hey @fabien-ml I was thinking if it would be possible for you do this for one component(say TextField.*)? then others(possibly me) can follow the same pattern and raise PRs for the other component. WDYT?

**Comment by fabien-ml** [comment]
done in `v0.7.1`

**Comment by mmrath** [comment]
Thank you @fabien-ml
