### ISSUE TITLE
on Safari, Tabs keyboard navigation is not working when navigation is initiated by click

### ISSUE THREAD

**Issue by simbas** [kobaltedev/kobalte#118]
**Describe the bug**
on Safari, Tabs keyboard navigation is not working when navigation is initiated by click

**To Reproduce**

1. Go to https://kobalte.dev/docs/core/components/tabs
2. Click on the Dashboard tab trigger of the first example
3. Try arrow keys to navigate between tabs
4. See that it is not navigating

**Expected behavior**
The active tab should change (as it does with Chrome).

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Version: 15.6.1

**Comment by fabien-ml** [comment]
fixed in `v0.7.3`
