### ISSUE TITLE
Menu ghost keyboard navigation focus

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#146]
**Describe the bug**
The Menus (Dropdown & Context) have ghost focus when navigation in SubMenus with keyboard in certain cases.

**To Reproduce**
1) Open a Menu and navigate with keyboard to a SubMenu
2) Spam left and right arrow
3) Arrow up or down

**Expected behavior**
Only one should be focused.

**Screenshots**
<img src="https://user-images.githubusercontent.com/33844379/226190006-6f577052-7add-4d0b-8b9a-c89ea690000e.png" width="500">

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox & Chrome
- Version: 111 & 111

**Comment by fabien-ml** [comment]
fixed in `v0.8.0`.
