### ISSUE TITLE
MultiSelect not working with touch

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#147]
**Describe the bug**
Unable to select or unselect a MultiSelect option with touch. A single touch will click and unclick the item.

**To Reproduce**
1) Open a MultiSelect
2) Click on option with touch

**Expected behavior**
Should work the same as with cursor.

**Screenshots**
![Screen Recording](https://user-images.githubusercontent.com/33844379/226217213-e3256f34-a1c2-4baa-87e2-a62b07707d63.mp4)

**Desktop:**

- OS: Windows
- Browser: Firefox & Chrome
- Version: 111 & 111

**Smartphone:**

- OS: Android
- Browser: Firefox
- Version: 111

**Comment by fabien-ml** [comment]
fixed in `v0.8.0`.
