### ISSUE TITLE
Use native HTML attribute names instead of `isX` or `hasX` to avoid confusion

### ISSUE THREAD

**Issue by fabien-ml** [kobaltedev/kobalte#166]
**Describe the bug**
Some components has both `isDisabled` and `disabled` props which is a bit confusing. It would be cleaner to expose just one.

**Expected behavior**
Expose only one prop when equivalent exist as HTML attribute (disabled, required, readOnly, etc...).

**Comment by jcmonnin** [comment]
Similar issue for Checkbox: attribute `onCheckedChange` vs `onChange`.

For the Kobalte checkbox, `onChange` is not reported, so my Checkbox migrated from Hope-UI didn't work before switching to `onCheckChange`. It would be better if TypeScript would catch it.

Reporting them on a case-by-case basis as they appear.
