### ISSUE TITLE
Dialog component

### ISSUE THREAD

**Issue by AlexGreb** [kobaltedev/kobalte#169]
I am using the dialog component inside the shadow-root. For this I use <Dialog.Portal mount={my custom element (shadow-root)}> to open dialog in my custom component. This works well, the dialog opens, but if you click on the contents of the dialog, it closes. This is because event.target is a custom element with shadow root

I would like to somehow control this behavior. for example, write composed: true for a custom event to track which shadow-root element was clicked on
<img width="1205" alt="Снимок экрана 2023-04-05 в 10 37 05" src="https://user-images.githubusercontent.com/14977840/230000539-50f8fcda-913d-491d-bb7f-402f46c58a40.png">

**Comment by fabien-ml** [comment]
Hi the `Dialog.Content` component has 3 props that may help you to apply a custom logic related to the "click outside" behavior: 
- onInteractOutside
- onFocusOutside
- onPointerDownOutside

**Comment by AlexGreb** [comment]
Thank you

**Comment by dvirtz** [comment]
The event target is always the shadow root so it's hard to implement custom logic other than always calling `preventDefault()` and handle those events manually.
I think the correct way would be to listen on `ref().getRootNode()` instead of `ownerDocument()`.
