### ISSUE TITLE
ESM Compliance: Use file extensions for relative imports

### ISSUE THREAD

**Issue by sachaw** [kobaltedev/kobalte#190]
**Describe the bug**
As per https://nodejs.org/api/esm.html#esm_mandatory_file_extensions file extensions are required for all relative import statements.
This presents itself as an issue when resolving type definitions in projects using `moduleResolution` set to `node16` or `nodenext`.

Typescript has deemed it out-of-scope to auto fix it for you during transpilation, and instead is on the user to change it in the source.

The two changes required are:
1. Append `.js` to all relative file imports
2. Append `/index.js` to all automatically resolving imports to index files.

I would be happy to open a PR if there are no objections.

Thanks.

**Comment by sachaw** [comment]
My PR only uses the `.js` extension, however it is common practice to import `.tsx` files as `.jsx`, this is only a preference, let me know if you would like me to follow this.

**Comment by jer3m01** [comment]
Changed building to `tsup` for esm, if there are still issues with tools please reopen.
