### ISSUE TITLE
[Modal]: separate hide outside and prevent scroll behavior from `modal` prop of overlay components

### ISSUE THREAD

**Issue by fabien-ml** [kobaltedev/kobalte#206]
**Is your feature request related to a problem? Please describe.**
Separate hide outside and prevent scroll behaviors from `modal` prop of overlay components (Dialog, Popover, Menu, Select...)

**Describe the solution you'd like**
Split the `modal` prop in two props:
- `modal`: aria-hide outside elements and disable pointer outside where needed.
- `preventScroll`: lock body scroll.

**Comment by katywings** [comment]
@fabien-ml Thank you for creating this 😊

**Comment by fabien-ml** [comment]
Most of the time the modal behavior should be what it is actually. Sine your use case is an edge case and to avoid breaking changes I'm thinking about doing it like this:

- `modal`: stay the same
- `preventScroll`: only prevent scroll. 

In your component you disable the modal mode and only enable scroll lock:

```tsx
<Dialog.Root modal={false} preventScroll />
```

Scroll will be lock if either one of the prop is true.

**Comment by katywings** [comment]
> Most of the time the modal behavior should be what it is actually
Indeed.

I appreciate your detailed answer, ty! That `preventScroll` prop would help a lot. If you are interested I can create a PR.
