### ISSUE TITLE
[Link] Add role="link" and remove href from Link when it's disabled

### ISSUE THREAD

**Issue by its-monotype** [kobaltedev/kobalte#213]
It is still possible to disable a link by following 3 steps:

- remove the href attribute so that it can no longer receive the focus
- add a role="link" so that it is always considered a link by screen readers
- add an attribute aria-disabled="true" so that it is indicated as being disabled
HTML

and we can remove custom onClick handler where we calling preventDefault

<a role="link" aria-disabled="true"> Disabled link</a>

Check out Scott O'Hara's excellent article on the subject: [Disabling a link](https://www.scottohara.me/blog/2021/05/28/disabled-links.html).

**Comment by fabien-ml** [comment]
Hi, thank it works like a charm.
