### ISSUE TITLE
Tab Indicator doesn't stay with selected tab

### ISSUE THREAD

**Issue by tesioai** [kobaltedev/kobalte#218]
**Describe the bug**
Tab indicator doesn't stay with the selected tab when tabs are dynamically updated.

**To Reproduce**

1. Select a tab
2. Update the tab list with less or more tabs than the index of the selected tab

**Expected behavior**
Expected the indicator to stay with the selected tab

**Screenshots**
https://streamable.com/9mte9i

**Desktop:**

- OS: Ubuntu
- Chrome
- Version 113.0.5672.92 (Official Build) (64-bit)

**Comment by fabien-ml** [comment]
Hi, thanks for reporting the issue.

Do you have a reproduction code, because the expected behavior seem to work fine in the doc https://kobalte.dev/docs/core/components/tabs#dynamic-tabs

**Comment by jer3m01** [comment]
Closing this issue as can't reproduce and stale, if the issue persist please comment or reopen.
