### ISSUE TITLE
[Combobox]: input doesn't update when value is controlled externally

### ISSUE THREAD

**Issue by lydianlights** [kobaltedev/kobalte#229]
**Describe the bug**
I'm using a combobox with multiple mode disabled. When you click on an option in the dropdown menu, the input text is set to the text of the selected option. However setting the value of the combobox through any other method than clicking the dropdown does not update the text input (in my case I'm using a button). This provides the user with no visual confirmation that the value has changed.

**To Reproduce**

1. Create a combobox with options `["one", "two", "three"]`
2. Control the value of the combobox with a signal
3. Create a button the clear or set the combobox value
4. The button clears or sets the value, but no change is made to the text input

**Expected behavior**
I would expect controlling the `value` prop externally to automatically change the input value when the `value` prop changes

**Screenshots**
My combobox:
![Screenshot_1](https://github.com/kobaltedev/kobalte/assets/21229800/a0230171-3b75-472e-960a-2c78d4022322)

Pressing the + adds a new item to the list and selects it, but the input is unchanged:
![Screenshot_5](https://github.com/kobaltedev/kobalte/assets/21229800/417d3978-1ee5-456d-a769-dbc4644e292f)

Clicking the item correctly updates the input:
![Screenshot_3](https://github.com/kobaltedev/kobalte/assets/21229800/bc87bbe8-1c4d-402d-a525-3b9d9279aab4)

Clicking the X correctly removes the selected item, but the input is not cleared:
![Screenshot_4](https://github.com/kobaltedev/kobalte/assets/21229800/ad7c54a3-887c-4916-9b70-7ffa3f5db1ac)

**Environment:**
Windows Firefox 114.0.2

**Additional context**
This can be worked around by adding a ref to the `Combobox.Input` element and manually setting the input value. However, it feels slightly strange that this would be required when the default selection method handles this automatically.

**Comment by fabien-ml** [comment]
@jcmonnin sorry, i've forgot to mention `disallowEmptySelection` in the release note.
The bug is fixed and i'm trying to fix 1,2 more before releasing a new version.

The problem was when you deselect an item, the value became `undefined` and when a Kobalte's component get `undefined` as value it work as an uncontrolled one. Now when you deselect the value became `null` which is fine.
