### ISSUE TITLE
Clearing Select controlled value.

### ISSUE THREAD

**Issue by simonbuchan** [kobaltedev/kobalte#241]
**Describe the bug**
I'm getting weird behavior when trying to clear a `<Select>` value: it instead displays the last selected value for that `<Select>` - eg. normally it appears not to change.

**To Reproduce**

1. Clone, and run https://github.com/simonbuchan/kobalte-testing/tree/select-clear-bug
2. Select an item with either or both `<Select>`s, controlling the same value.
3. Click "Clear Value"
4. Notice any `<Select>` that you have interacted with will not show the "empty" placeholder, though the `Value: ` output will show it has been cleared. In particular, they will show the last value you've selected with that specific control.

**Expected behavior**
It should be possible to de-select a value for a `<Select />` - perhaps not 

**Screenshots**

Both selects controlled by the same value, the first option was used to select a value, then "Clear Value" was clicked:
<img width="149" alt="image" src="https://github.com/kobaltedev/kobalte/assets/1840547/ece415ba-ddad-4afe-adf4-7472c76a015b">

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 115.0.5790.110 

**Smartphone (please complete the following information):**

(not attempted)

**Additional context**

Using `null` vs `undefined` or object-valued options doesn't seem to make any difference here, so far as I've checked. Using an initial value only means you can reset without interacting with it, so it seems to work then.

I've noticed a lot of fairly weird behavior around `<Select>` in general, it seems like it's trying to do too much at the moment. It explodes with a `null` option value, it has a non-`string` `value` unlike every other control, also inconsistent with it's other uses of `value`, it sometimes and sometimes doesn't show the `focus-visible` style with mouse interactions, etc....

**Comment by AuTa** [comment]
> it sometimes and sometimes doesn't show the focus-visible style with mouse interactions.

Sure, I also encountered this problem. After the page is refreshed, clicking `<Select>` and then clicking elsewhere will trigger `focus-visible`. However, when I click another `<Button>`, `focus-visible` is not triggered anymore. Additionally, I have removed `<Select-Value>`, so there isn't an input field present.
