### ISSUE TITLE
Dialog shifts to the left at start of closing due to scrollbar in Windows

### ISSUE THREAD

**Issue by zamanruhy** [kobaltedev/kobalte#243]
**Describe the bug**
Dialog component restores the scrollbar of the page at the start of the close animation, resulting in an annoying shift to the left on Windows (see screenshot)

**To Reproduce**
Try opening and closing dialog in the documentation in Windows (or MacOS with obtrusive scrollbar enabled)

**Expected behavior**
The scrollbar should be restored after the dialog is completely closed (e.g. like bootstrap modal)

**Screenshots**

https://github.com/kobaltedev/kobalte/assets/5624053/2070c938-10d1-42e3-aaa4-8da1c5bdf3e3

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome latest

**Comment by jer3m01** [comment]
Changed the scroll lock implementation and this seems fixed.
