### ISSUE TITLE
Sponsorship Roadmap

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#247]
Outline of work to be done on Kobalte, sponsored by @davedbase.
Will keep this issue updated with linked PRs rather than a single huge PR.

## Roadmap

Components that are planned for the sponsorship as well as implementation requirements and resources.

### Pagination ✅
https://github.com/kobaltedev/kobalte/pull/239
#269

+ Feature request https://discord.com/channels/722131463138705510/1063803756388548709/1140407086052823080 (always show same number of items to avoid content shift)

Work done ~11h

### Menubar ✅

#260

Will be based on https://www.radix-ui.com/primitives/docs/components/menubar and follow https://www.w3.org/WAI/ARIA/apg/patterns/menubar/.

+ Extra option boolean than radix for focus on `Alt`.

+ PR will also include documentation and tests.

While it is much bigger than Pagination, most of the work has already been done in the ContextMenu & DropdownMenu component. Only the Menubar itself and its interaction need to be added.

Work done ~13h

## Additional work

`@kobalte/date` (DatePicker, Calendar) and bug fixes / other chores will be added in the future.

Anything else mentioned by @fabien-ml or @davedbase and approved can be added to this list.

**Comment by fabien-ml** [comment]
For `Calendar`: tests & doc are missing.

For `DatePicker` (my current WIP): multiple selection, range selection, tests & doc are missing. 

I'm ok with the rest mentioned above.

**Comment by jer3m01** [comment]
Closing this part as done, new issues to be created for continuation.
