### ISSUE TITLE
ComboBox Value Not Reflecting on Every Change

### ISSUE THREAD

**Issue by SreeniIO** [kobaltedev/kobalte#250]
Description:

When using the controlled ComboBox component, there's an inconsistent behavior observed. Changing the value of the ComboBox seems to reset the ComboBox's value every other time.

## Steps to Reproduce:

Navigate to [the provided playground](https://stackblitz.com/edit/kobalte-playground-cwscoa?file=src%2FApp.tsx).
Select any value from the ComboBox.
Click the links below the ComboBox.
Notice that every odd click resets the ComboBox to an empty value.

## Expected Behavior:

The ComboBox should consistently display the changed value every single time.

## Actual Behavior:

Every odd click on the link below the ComboBox empties the ComboBox value.

## Additional Information:

Link to the playground for reproduction: [here](https://stackblitz.com/edit/kobalte-playground-cwscoa?file=src%2FApp.tsx)
@kobalte/core: 0.10.0
solid-js: 1.7.11

**Comment by SreeniIO** [comment]
This issue is still reproducible with @kobalte/core: 0.11.0

https://stackblitz.com/edit/kobalte-playground-cwscoa?file=package.json

**Comment by SreeniIO** [comment]
Ok. It works fine, if I remove the filter and use the defaultFilter prop and pass all options.

**Comment by fabien-ml** [comment]
Hi, sorry i'm currently struggling to deploy the new documentation web site.
Here is an updated playground: https://stackblitz.com/edit/kobalte-playground-url9mn?file=src%2FApp.tsx.
