### ISSUE TITLE
Text highlighted after choosing a select option

### ISSUE THREAD

**Issue by benalleng** [kobaltedev/kobalte#266]
**Describe the bug**
When choosing a select option the cursor behaves as though it is being held and begins to highlight text around the select.root

Functions normally in Chrome

**To Reproduce**
1. Click a select field where a root has some siblings or parent elements with Text 
2. choose an option, upon the list-box closing move the cursor around and the text will be higlighted

A quick sandbox showing the behavior

https://codesandbox.io/p/sandbox/sad-water-z2rkg4?file=/src/App.tsx:21,25

![firefox-select-repro](https://github.com/kobaltedev/kobalte/assets/108441023/57c883bd-9262-4913-8f66-9c0eea4dbdb4)

**Expected behavior**
Focus should remain on the select trigger and the cursor should not highlight other text

- OS: MX Linux
- Browser Firefox
- Version 116.0.3

**Comment by jer3m01** [comment]
You can add `user-select: none;` to the select item, such as in https://kobalte.dev/docs/core/components/select#controlled-value.

**Comment by benalleng** [comment]
Works! thanks!
