### ISSUE TITLE
Make TextField more float frendly

### ISSUE THREAD

**Issue by untlsn** [kobaltedev/kobalte#288]
Currently, it is not possible to put a dot at the end of the input when the type is number. And from what I understand, it's a problem on the browser side, because `target.value` removes the dot at the end. So is it acceptable to ignore the change when target.value are the same?
```ts
// Inside text-field-input.tsx
onInput={(ev) => {
	const target  = ev.target as HTMLInputElement;
	if (target.value == context.value()) return;
	local.onInput?.(ev);
	context.onInput?.(ev);
}}
```

**Comment by probably-neb** [comment]
@untlsn, Thanks! The fix you proposed is working correctly for me. I'd be happy to open a pr for this if you're not interested in doing so

**Comment by jer3m01** [comment]
`<TextField/>` is only intended for strings, for numbers (including any unit/formatting) use `<NumberField/>`.
