### ISSUE TITLE
[Component] Meter

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#316]
https://react-spectrum.adobe.com/react-aria/Meter.html

**Comment by Shubhdeep12** [comment]
hey @jer3m01 is this open for contribution?

**Comment by jer3m01** [comment]
> hey @jer3m01 is this open for contribution?

Yes, PRs welcomed!

**Comment by Shubhdeep12** [comment]
Great!

The Meter and Progress Bar components are similar but serve different use cases. The Meter will not have any progress states and will always display determinate data.
I've raised the first draft, and we can discuss further in the PR.

Thanks!
