### ISSUE TITLE
chore(collapsible): use <details> & <summary>

### ISSUE THREAD

**Issue by infograafikko** [kobaltedev/kobalte#326]
**Is your feature request related to a problem? Please describe.**
Collapsible box has been implemented using div's but `<details>` tag has now wide support. Would it be easier for screen readers and inspectors to make the element using `<details>` tag?

**Describe the solution you'd like**
Replace `<div>` solution with `<details>`

Link describing `<details>` tag https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Example: 
<details>
<summary>What is Kobalte?</summary>
Kobalte is a UI toolkit for building accessible web apps and design systems with SolidJS. It provides a set of low-level UI components and primitives which can be the foundation for your design system implementation.</details>

**Comment by jer3m01** [comment]
It seems that `<details>` and `<summary>` aren't flexible enough for Kobalte's implementation and flexibility.
Closing as not planned since the the current implementation is already fully accessible.
Will reconsider if native `<details>` become more flexible.
