### ISSUE TITLE
Menubar: Incorrect trigger expanded on keyboard navigation

### ISSUE THREAD

**Issue by fnky** [kobaltedev/kobalte#332]
**Describe the bug**

Tabbing into a menubar will focus the latest expanded trigger. When the trigger is focused, but not expanded, then navigating with keyboard will highlight the other triggers; but using keyboard to expand the item (Enter/Space/Arrow down) will only expand the focused trigger. 

**To Reproduce**

1. On initial page load, tab into menubar trigger
2. Use keyboard (e.g. left/right) to highlight another trigger
3. Trigger the button with keyboard (Enter/Space/Arrow down) to try and expand the highlighted trigger.
4. It expands the focused trigger, even if it isn't the current highlighted one.

**Expected behavior**

It should expand the highlighted item, rather than what was initially focused.

**Screenshots**
<video src="https://github.com/kobaltedev/kobalte/assets/995050/3db8f33e-5615-4ba5-ae72-467924b08c1e"></video>

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser Brave
- Version 1.57.64 (Chromium 116.0.5845.188)

**Additional context**
See [Radix UI Menubar](https://www.radix-ui.com/primitives/docs/components/menubar) as an example of expected behavior.

**Comment by jer3m01** [comment]
Thanks for the excellent bug report!
