### ISSUE TITLE
Menubar: Incorrect trigger interaction on menu close

### ISSUE THREAD

**Issue by fnky** [kobaltedev/kobalte#333]
**Describe the bug**

When closing the menu there are two cases where the menu will close visually but stay in a state as if the menu is open.

1. Clicking on the trigger will continue to open menus when hovering over other triggers.
2. Closing the menu with Escape will stop keyboard navigation and highlight other triggers, without opening the menu.
 
**To Reproduce**

First case;

1. Click on a trigger to open its menu.
2. Click on the trigger again to close the menu.
3. Hover other triggers; it will open their menus.

Second case;

1. Click on a trigger to open its menu.
2. Press Escape to close the menu.
3. Hover other triggers; Will highlight items on hover, but keyboard navigation and interaction doesn't work.

**Expected behavior**

For the first case, after closing the menu on the trigger, other triggers should not open when hovered.

For the second case, it should close the menu, and keep keyboard navigation functioning.

**Screenshots**

##### First case

<video src="https://github.com/kobaltedev/kobalte/assets/995050/e681564c-d77c-4695-bcd1-d3f17ddaac7f"></video>

##### Second case

<video src="https://github.com/kobaltedev/kobalte/assets/995050/7637864a-dac7-42db-a4d3-b759367e9539"></video>

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser Brave
- Version 1.57.64 (Chromium 116.0.5845.188)

**Additional context**
See [Radix UI Menubar](https://www.radix-ui.com/primitives/docs/components/menubar) as an example of expected behavior.

**Comment by jer3m01** [comment]
Thanks again!
