### ISSUE TITLE
Slider `onChangeEnd` not fired if changing value via arrow keys

### ISSUE THREAD

**Issue by gBasil** [kobaltedev/kobalte#352]
**Describe the bug**
If the thumb of a slider is selected (given tab focus) and then the value is changed with the arrow keys, `onChangeEnd` is never fired with the new value.

**To Reproduce**

1. Create a slider:
```tsx
<Slider.Root onChangeEnd={console.log}>
  <Slider.Track>
    <Slider.Thumb class={style.thumb}>
      <Slider.Input />
    </Slider.Thumb>
  </Slider.Track>
</Slider.Root>
```
2. Select the `Slider.Thumb` with your keyboard.
3. Use the left and right arrow keys to change the value.
4. Observe how `onChangeEnd` is never fired and nothing is logged to the console.

**Expected behavior**
I'm not sure what the recommended accessibility guidelines are for this, but either:
1. Fire `onChangeEnd` every time the value changes from the arrow keys .
2. Fire `onChangeEnd` once the thumb loses focus, (and potentially also whenever the enter or space is pressed).

**Desktop:**

- OS: macOS
- Browser: Vivaldi (Chromium)
- Version: 6.6.3271.45 (Stable channel)

**Comment by jer3m01** [comment]
@dev-rb I'm not sure how it's intended to work. 
Looking at other framework implementations we match by only calling `onChangeEnd` at pointer up.

Let me know if it's as intended!

**Comment by dev-rb** [comment]
I also followed the other implementations. While I think it makes sense to fire ``onChangeEnd``, I'm not sure about the implications from an accessibility standpoint.

We could go with firing ``onChangeEnd`` when the thumb loses focus I suppose

**Comment by gBasil** [comment]
Another potential pattern could be to fire `onChangeEnd` when either:
- The thumb loses focus
- The enter or space keys are pressed while the thumb is focused.
