### ISSUE TITLE
[Component]: Status Badge

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#363]

**Comment by Shubhdeep12** [comment]
Hey @jer3m01 I hope this is the expectation here - https://spectrum.adobe.com/page/badge/

**Comment by jer3m01** [comment]
> Hey @jer3m01 I hope this is the expectation here - [spectrum.adobe.com/page/badge](https://spectrum.adobe.com/page/badge/)

Yes but without any preset "variants" and an optional prop called `textValue` (`string`) for auto populating the appropriate `aria-label` attribute.
This would probably be a single 1 file component.

**Comment by Shubhdeep12** [comment]
cool, thanks for the info.
