### ISSUE TITLE
No ToggleGroup in npm package

### ISSUE THREAD

**Issue by TAMspurt** [kobaltedev/kobalte#383]
**Describe the bug**
ToggleGroup not included in npm dist package.

**To Reproduce**

1. Import ToggleGroup from npm package @kobalte/core

**Expected behavior**
ToggleGroup must persists in npm package

**Comment by dmackinn** [comment]
I have this same issue, there's no export in core->dist->types for it.

**Comment by jer3m01** [comment]
ToggleGroup has been release in `0.13.0`
