### ISSUE TITLE
Combobox: trigger mode 'focus' prevents dropdown list from closing

### ISSUE THREAD

**Issue by daelmaak** [kobaltedev/kobalte#387]
**Describe the bug**
I use combobox as a way to have both a select and filter input field in one. I also want the dropdown list to open when user starts interacting with the combobox. So I tried to use `focus` trigger mode. It works as expected until user selects an option, because then the focus is moved away from the closing dropdown to the combobox input, which in turn reopens the dropdown again due to the focus trigger mode, this time with only 1 option.

![image](https://github.com/kobaltedev/kobalte/assets/34311965/977c18e0-6efb-48b2-85c3-1f67b78dcb95)

So to the user it might look like she needs to confirm that selection by clicking the last remaining option and after she does it, the option deselects. Or user has to just leave the dropdown open and carry on, which is not great experience.

**To Reproduce**

1. With `triggerMode === 'focus'`, click on a combobox
2. Select an option
3. Dropdown list didn't close

**Expected behavior**
When an option is selected from dropdown list, the list should close, even despite the 'focus' trigger mode.

**Desktop (please complete the following information):**

- OS: Win 11
- Browser Brave

**Comment by 0-don** [comment]
yes currently doing this

```tsx
export const MyCombobox: Component<
  ComboboxPrimitive.ComboboxRootProps<any, any>
> = (props) => {
  const [open, setOpen] = createSignal(false);
  return (
    <Combobox
      {...props}
      open={open()}
      onClick={() => setOpen(!open())}
      onOpenChange={(e) => setOpen(e)}
      itemComponent={(props) => (
        <ComboboxItem item={props.item}>
          <ComboboxItemLabel>{props.item.rawValue}</ComboboxItemLabel>
          <ComboboxItemIndicator />
        </ComboboxItem>
      )}
    >
      <ComboboxControl>
        <ComboboxInput />
        <ComboboxTrigger />
      </ComboboxControl>
      <ComboboxContent />
    </Combobox>
  );
};
```
