### ISSUE TITLE
Bigger bundle size compared to solid-headless

### ISSUE THREAD

**Issue by thetarnav** [kobaltedev/kobalte#40]
I'm currently using solid-headless for a simple DropdownMenu. It is very basic, it doesn't need floating-ui dep as I can position the menu myself with CSS.
Tried comparing the bundle size of it and kobalte's equivalent, because I might want to switch to using kobalte in the future (better documented, maintained, etc)
But the DropdownMenu from kobalte appears to be ~8x times larger in bungle size. I was using https://bundlejs.com which supports tree-shaking.

- [solid-headless build](https://bundlejs.com/?q=solid-headless&treeshake=%5B%7B+Menu%2CMenuItem%2CPopover%2CPopoverButton%2CPopoverPanel+%7D%5D&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22solid-js%22%2C%22solid-js%2Fweb%22%2C%22solid-js%2Fstore%22%5D%2C%22conditions%22%3A%5B%22browser%22%5D%7D%7D)
```ts
export { Menu, MenuItem, Popover, PopoverButton, PopoverPanel } from 'solid-headless'
// Bundle size is 22.92KB -> 5.32KB (gzip)
```
- [koblate build](https://bundlejs.com/?q=%40kobalte%2Fcore&treeshake=%5B%7B+DropdownMenu+%7D%5D&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22solid-js%22%2C%22solid-js%2Fweb%22%2C%22solid-js%2Fstore%22%2C%22%40solid-primitives%2Frootless%22%2C%22%40solid-primitives%2Fimmutable%22%2C%22%40solid-primitives%2Frefs%22%2C%22%40solid-primitives%2Fprops%22%2C%22%40solid-primitives%2Fmedia%22%2C%22%40solid-primitives%2Fevent-listener%22%2C%22%40solid-primitives%2Futils%22%5D%2C%22conditions%22%3A%5B%22browser%22%5D%7D%7D)
```ts
export { DropdownMenu } from "@kobalte/core"
// Bundle size is 155.96KB -> 40.95KB (gzip)
```
(this is with adding solid-js and solid-primitives to `external` as I already use them)

Not exactly sure what causes that difference honestly. The `@floating-ui/core` dep is adding only ~3KB gzip, `@kobalte/utils` is also ~3KB gzip, the `@internationalized` thing is barely adding anything. So the biggest chunk must be in the main package.
Is there a way to improve tree-shaking? I get that kobalte may be stacked with more features, but not everyone will use them.

**Comment by fabien-ml** [comment]
Hi, i'm not sure what causes this. 
I tried on a fresh solidjs project and only import the dropdown menu, in the production build there is only the code needed for the menu but the bundle is about 115kb 😕 (same when using select, or others "floating" components).

**Comment by marbemac** [comment]
Part of it might be the legal comments getting left in by default by vite.

Configuring esbuild to remove them reduces the bundle size of solid + DropdownMenu to ~34kb gzipped.

```ts
import analyze from "rollup-plugin-analyzer";
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";

export default defineConfig({
  plugins: [solidPlugin(), analyze({ summaryOnly: true })],
  server: {
    port: 3000,
  },
  esbuild: {
    legalComments: "none",
  },
  build: {
    target: "esnext",
    // minify: false,
  },
});
```

Still quite a bit larger than `solid-headless` though, not sure how solid-headless gets away with much less code, would have to dig into their implementation 🤷‍♂️.

Here's some of the output from `rollup-plugin-analyzer` in case it's helpful:

<img width="1271" alt="Screenshot 2023-01-13 at 8 38 40 PM" src="https://user-images.githubusercontent.com/847542/212444717-9313bdfc-e5f5-44b4-bf57-b80c42c9555f.png">

**Comment by fabien-ml** [comment]
I'm working on a refactor of the way components are exported. Currently when you import `DropdownMenu` you get all parts even if not used.

**Comment by fabien-ml** [comment]
Tree shaking is better in v`0.3.0`

**Comment by fabien-ml** [comment]
@thetarnav can i close the issue ?

**Comment by thetarnav** [comment]
You decide.
I believe that the tree-shakeability and overall bundle size could be still improved.
[Based on bundlejs.com the bundlesize actually increased](https://bundlejs.com/?q=%40kobalte%2Fcore&treeshake=%5B%7B+DropdownMenu+%7D%5D&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22solid-js%22%2C%22solid-js%2Fweb%22%2C%22solid-js%2Fstore%22%2C%22%40solid-primitives%2Frootless%22%2C%22%40solid-primitives%2Fimmutable%22%2C%22%40solid-primitives%2Frefs%22%2C%22%40solid-primitives%2Fprops%22%2C%22%40solid-primitives%2Fmedia%22%2C%22%40solid-primitives%2Fevent-listener%22%2C%22%40solid-primitives%2Futils%22%2C%22%40swc%2Fhelpers%22%5D%2C%22conditions%22%3A%5B%22browser%22%5D%2C%22legalComments%22%3A%22none%22%7D%7D), but not sure how reliable this is.
If you don't plan on reducing it now then there is no point in keeping the issue.

**Comment by fabien-ml** [comment]
> You decide. I believe that the tree-shakeability and overall bundle size could be still improved. [Based on bundlejs.com the bundlesize actually increased](https://bundlejs.com/?q=%40kobalte%2Fcore&treeshake=%5B%7B+DropdownMenu+%7D%5D&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22solid-js%22%2C%22solid-js%2Fweb%22%2C%22solid-js%2Fstore%22%2C%22%40solid-primitives%2Frootless%22%2C%22%40solid-primitives%2Fimmutable%22%2C%22%40solid-primitives%2Frefs%22%2C%22%40solid-primitives%2Fprops%22%2C%22%40solid-primitives%2Fmedia%22%2C%22%40solid-primitives%2Fevent-listener%22%2C%22%40solid-primitives%2Futils%22%2C%22%40swc%2Fhelpers%22%5D%2C%22conditions%22%3A%5B%22browser%22%5D%2C%22legalComments%22%3A%22none%22%7D%7D), but not sure how reliable this is. If you don't plan on reducing it now then there is no point in keeping the issue.

The overall size of the lib is larger because the code related to calendar/datepicker that i'm working on was added.
I don't think tree shaking is working correctly on bundlejs.com, on your example components like `Tabs` or `RadioGroup` is in the output, which is not the case when i build a real solidjs project.
