### ISSUE TITLE
When is the menu component exported?

### ISSUE THREAD

**Issue by bytegolang** [kobaltedev/kobalte#410]
If I implement a sidebar, what components do I need to use to support expansion and collapse?

**Comment by bytegolang** [comment]
If I implement a sidebar, what components do I need to use to support expansion and collapse?

**Comment by jer3m01** [comment]
For sidebar that appear as a popup use a `Dialog` ([example here](https://github.com/kobaltedev/kobalte/blob/025db21aeb80db1ac2a9100a87814852cae1e6d6/apps/docs/src/components/mobile-navigation.tsx#L41)) ([docs](https://kobalte.dev/docs/core/components/dialog)).

For sidebars that are always visible but expand/collapse use a `Collapsible` ([docs](https://kobalte.dev/docs/core/components/collapsible)).
