### ISSUE TITLE
Browser Version Compatibility

### ISSUE THREAD

**Issue by robodna** [kobaltedev/kobalte#419]
Hello,

Where do I find a list of compatible browser versions for Kobalte components?

Thank you,

**Comment by jer3m01** [comment]
Kobalte uses the default targets of vite (`Chrome >=87`, `Firefox >=78`, `Safari >=14`, `Edge >=88`) https://vitejs.dev/guide/build.html#browser-compatibility.

For targeting older browsers https://polyfill.io/ is recommended.
