### ISSUE TITLE
Trouble building @kobalte/core in forked repo

### ISSUE THREAD

**Issue by jsimonrichard** [kobaltedev/kobalte#430]
**Describe the bug**
I recently forked Kobalte (https://github.com/jsimonrichard/kobalte), but I can't build the core package on machine (or any other package depending on `@kobalte/tests`) without changing the dependency to "file:../tests." This fixes it on my machine, but breaks the CI build.

It appears that `@kobalte/tests` is a private package on NPM. Would you consider making that package public so that people outside of your organization can build `@kobalte/core`?

Or is this a new regression (I noticed there are already quite a few forks, nobody has raised this issue yet as far as I can tell)?

**Comment by jer3m01** [comment]
`@kobalte/tests` is a local monorepo package (not on npm), make sure you're using `pnpm@8` as a package manager.

**Comment by jsimonrichard** [comment]
It's working now, thank you. I wasn't using `pnpm`
