### ISSUE TITLE
Combobox incorrect type

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#438]
Kobalte's combobox only clears the input when given a value of null, but this conflicts with the fact that combobox expects a value of type `Option | undefined`, and not `Option | null`: https://stackblitz.com/edit/kobalte-combobox-undefined-value-bug?file=src%2FApp.jsx

Also, the type of the `onChange` prop is `(option: Option) => void` even though option is sometimes null (for example, when a selected option is deselected).

[source](https://discord.com/channels/722131463138705510/1063803756388548709/1254313948891578409)

**Comment by jcmonnin** [comment]
This is linked to #412, which is a similar issue for Select
