### ISSUE TITLE
Inputs inside accordions require multiple clicks to focus

### ISSUE THREAD

**Issue by Brendonovich** [kobaltedev/kobalte#440]
**Describe the bug**
An `<input>` within an accordion requires being clicked twice to receive focus. I'm not entirely sure why but it seems like AccordionTrigger hijacks the first click's onFocusIn.

**To Reproduce**
Try focusing and unfocusing the input in this repro by clicking in and out of it: https://stackblitz.com/edit/github-fk8exj-ruezfg?file=src%2Froutes%2Findex.tsx

**Expected behavior**
The input should instantly focus, rather than requiring 2 clicks

**Comment by army-u8** [comment]
I also found this problem, is there a any solution?

**Comment by katywings** [comment]
I think this is a duplicate of #236 🤔

**Comment by jer3m01** [comment]
fixed by #483
