### ISSUE TITLE
Tailwindcss Plugin `data-animate` and `data-visible` not correct

### ISSUE THREAD

**Issue by XHanL** [kobaltedev/kobalte#453]
**Describe the bug**

When we use `ui-animate` or `ui-visible`, the tailwind plugin will generate `&[data-animate]` or `&[data-visible]`.
But the component like `Skeleton` only work with `&[data-animate="true"]` and `&[data-visible="true"]`.

**To Reproduce**

1. Create a Skeleton component.
2. Create some style with tailwind, `ui-animate` or `ui-visible` not work.
3.  Replace `ui-animate` to `[&[data-animate=true]]` or `ui-visible` to `[&[data-visible=true]]`, work as expect.

**Expected behavior**
- `ui-animate`should work when the Skeleton can animate.
- `ui-visible` should work when the Skeleton is visible.

**Screenshots**
[Kobalte Skeleton Example](https://kobalte.dev/docs/core/components/skeleton), the css use `[data-animate="true"]` or `[data-visible="true"]`.
<img width="691" alt="1111" src="https://github.com/user-attachments/assets/c9cf2147-2b8f-4879-bd00-507bd015d8b3">

[Tailwind plugin](https://github.com/kobaltedev/kobalte/blob/7ceb24941ed02a4732bf5ac4236f9eeea40afc5d/packages/tailwindcss/src/index.ts), the `ui-animate` or `ui-visible` will generate `&[data-animate]` or `&[data-visible]`.
<img width="757" alt="2222" src="https://github.com/user-attachments/assets/36983f3e-9ae3-4490-afe0-c95a294a20ad">

**Desktop (please complete the following information):**

- OS: Macos 14.5 (23F79)
- Browser: Safari
- Version: 
  - @kobalte/core@0.13.4
  - @kobalte/tailwindcss@0.9.0

**Comment by jer3m01** [comment]
This looks like an implementation difference from `Skeleton`, I'll try to make it the same as all others.
