### ISSUE TITLE
TextField display [object Event]

### ISSUE THREAD

**Issue by kapilpipaliya** [kobaltedev/kobalte#459]
**Describe the bug**
When `<TextField.Input onChange={setValue}/>` is passed TextInput displays `[object Event]` inside it.

```
function ControlledExample() {
	const [value, setValue] = createSignal();
	return (
		<>
			<TextField value={value()} onChange={setValue}>
				<TextField.Input onChange={setValue}/>
			</TextField>
			<p>Your favorite fruit is: {value()}.</p>
		</>
	);
}
```

**Expected behavior**
It should ignore passed `onChange` and display proper value.

**Screenshots**
<img width="200" alt="image" src="https://github.com/user-attachments/assets/f4fa8996-f210-482b-989f-f99ec49ebb7c">

**Comment by kapilpipaliya** [comment]
`TextFieldContext` should be exported. so we can overwrite `TextFieldInput` component if required.

**Comment by jer3m01** [comment]
`setValue` should only be called from the `onChange` of `TextField` and not `TextField.Input`.

The root `onChange` recieves a value with kobalte handling whereas the one from the input is the native event and should only be used for advanced custom handling.

**Comment by kapilpipaliya** [comment]
Can we all export for example `TextFieldContext`  ?

**Comment by jer3m01** [comment]
> Can we export all context for example `TextFieldContext` ?

That's planned [#321](https://github.com/kobaltedev/kobalte/issues/321), will need time to design the API, no ETA.
