### ISSUE TITLE
Some (Many?) components don't work with Astro + Hybrid rendering due to `window` call. 

### ISSUE THREAD

**Issue by wkelly17** [kobaltedev/kobalte#460]
Builds in Astro (using cloudflare as adapter) fail due to Kobalte lib code calling window apis. 

**To Reproduce**
Repro here: https://github.com/wkelly17/Kobalte-repro
Clone, pnpm i, and try to build.

**Expected behavior**
I'd expect it to build with SSR sections being properly split off as needed. 

**Desktop (please complete the following information):**
- OS: Mac Os

**Additional context**
    "@astrojs/cloudflare": "^11.0.4",
    "@astrojs/solid-js": "^4.4.1",
    "@kobalte/core": "^0.13.4",
    "astro": "^4.13.4",
    "solid-js": "^1.8.21",

**Comment by wkelly17** [comment]
Actually, this is probably an upstream issue with the solid / astro / cloudflare together:
https://discord.com/channels/722131463138705510/1241033968317632635/1262890061767245937

Sorry for the extra noise.

**Comment by gnosticdev** [comment]
This has been fixed in [@astrojs/solid-js@7.0.2](https://github.com/withastro/astro/pull/17584/changes/8a486ea374cf0117ab1ad82eb055ea904da8b9ee)
