### ISSUE TITLE
Bug in Pagination component if count < 6

### ISSUE THREAD

**Issue by pgswow** [kobaltedev/kobalte#461]
Hello! i use pagination component with fixedItems props. if count={} of total pages <= 6 i see this (on screen shot). can this be fixed?

Reproduce: https://stackblitz.com/edit/solidjs-templates-h6gz6h?file=src%2FApp.jsx

![2024-08-15_13-27-32](https://github.com/user-attachments/assets/301be026-e782-4ccc-a7c6-872b6a7570d1)

**Comment by dannextlogic** [comment]
I can confirm the issue

**Comment by dannextlogic** [comment]
@pgswow you didn't provide `page={1}` and `defaultPage={1}`, you can also remove the `fixedItems` items parameter.

Here's a [fixed demo](https://stackblitz.com/edit/solidjs-templates-6pah9x?file=src%2FApp.jsx)

**Comment by madaxen86** [comment]
> @pgswow you didn't provide `page={1}` and `defaultPage={1}`, you can also remove the `fixedItems` items parameter.
> 
> Here's a [fixed demo](https://stackblitz.com/edit/solidjs-templates-6pah9x?file=src%2FApp.jsx)

Well, removing fixedItems is not a fix.
This is clearly a bug.
Imagine you fetch items from an api. You won't know how many items/pages will be there.
If you choose to have fixed items, the pagination component should not return invalid indexes.
I'll try to provide a PR, but this is very tricky for edge cases.

**Comment by dannextlogic** [comment]
Please investigate another issue: when you delete last item on a page>=2, the pagination component will crash, showing some error `RangeError: Invalid array length` with these lines:

```js
// 
	return (
		<>
			<Show when={showFirst()}>{context.renderItem(1)}</Show>

			<Show when={showFirstEllipsis()}>{context.renderEllipsis()}</Show>

			<For each={[...Array(previousSiblingCount()).keys()].reverse()}>
				{(offset) => <>{context.renderItem(context.page() - (offset + 1))}</>}
			</For>

			{context.renderItem(context.page())}

                         {'RIGHT HERE'}
			<For each={[...Array(nextSiblingCount()).keys()]}>
				{(offset) => <>{context.renderItem(context.page() + (offset + 1))}</>}
			</For>
                         {'RIGHT HERE'}

			<Show when={showLastEllipsis()}>{context.renderEllipsis()}</Show>

			<Show when={showLast()}>{context.renderItem(context.count())}</Show>
		</>
	);
```

**Comment by madaxen86** [comment]
> Please investigate another issue: when you delete last item on a page>=2, the pagination component will crash, showing some error `RangeError: Invalid array length` with these lines:
> 
> ```js
> // 
> 	return (
> 		<>
> 			<Show when={showFirst()}>{context.renderItem(1)}</Show>
> 
> 			<Show when={showFirstEllipsis()}>{context.renderEllipsis()}</Show>
> 
> 			<For each={[...Array(previousSiblingCount()).keys()].reverse()}>
> 				{(offset) => <>{context.renderItem(context.page() - (offset + 1))}</>}
> 			</For>
> 
> 			{context.renderItem(context.page())}
> 
>                          {'RIGHT HERE'}
> 			<For each={[...Array(nextSiblingCount()).keys()]}>
> 				{(offset) => <>{context.renderItem(context.page() + (offset + 1))}</>}
> 			</For>
>                          {'RIGHT HERE'}
> 
> 			<Show when={showLastEllipsis()}>{context.renderEllipsis()}</Show>
> 
> 			<Show when={showLast()}>{context.renderItem(context.count())}</Show>
> 		</>
> 	);
> ```

Well that's probably because you pass a page to the Pagination component which does not exist anymore after removing the item.
An example:
You have 11 items in an array.
You render 10 items per page.
currentPage=2
```ts <Pagination
    count={ Math.ceil( items().length / 10 )}
    page={currentPage}
...
```
Now if you delete the last item you'll only have 1x page left but page still points to page 2 - thus the error.
--> you need to recalculate the page when deleting items, e.g. simple fix:
```ts <Pagination
   count={ Math.ceil( items().length / 10 )}
    page={Math.min(currentPage, Math.ceil( items().length / 10 ))}
...
```
Now page can't be bigger than count.
I've added a fix for the internal page as well. So the PR will cover this as well. 
PS: This was also an issue with more pages.

**Comment by pgswow** [comment]
> @madaxen86 I don't need to do anything, I already recoded the component set with ARK-UI and it works as I expected. I would suggest that you turn all incoming props to signals and the problem will solve itself. I had similar issues with other components of mine, signals fixes most of them.

Hello! in Ark-UI is your Select component working? it doesn't pass the hidden field to the form

**Comment by dannextlogic** [comment]
> Hello! in Ark-UI is your Select component working? it doesn't pass the hidden field to the form

I didn't test that yet.

**Comment by pgswow** [comment]
> > Hello! in Ark-UI is your Select component working? it doesn't pass the hidden field to the form
> 
> I didn't test that yet.

Check it out, you might be surprised that it doesn’t work the way it should logically work =) the Ark-ui community neither on discord nor on github comments anything about this =(
