### ISSUE TITLE
Combobox filter doesn't work in v0.9.6

### ISSUE THREAD

**Issue by army-u8** [kobaltedev/kobalte#485]
**Describe the bug**
 There is no automatic filtering option when enter input in `"@kobalte/core": "0.9.6"`.The latest version is normal, but this will affect the project after upgrading .Is there any way to solve it without upgrading?  thx.
**To Reproduce**
https://stackblitz.com/edit/solidjs-templates-axr63k?file=src%2FApp.tsx

**Comment by jer3m01** [comment]
This seems fixed in `0.11.2`, which includes minimal breaking changes: https://kobalte.dev/docs/changelog/0-11-x#v0110-august-25-2023.
