### ISSUE TITLE
docs(Breadcrumbs): use compound component <Breadcrumbs.Root>

### ISSUE THREAD

**Issue by dddieon** [kobaltedev/kobalte#521]
https://github.com/kobaltedev/kobalte/blob/9abd5d0d85adb08e1a6ba9be3544ee5c38ff76d4/apps/docs/src/examples/breadcrumbs.tsx#L8

This line appears to need `<Breadcrumbs.Root>` instead of `<Breadcrumbs>`.

**Comment by jer3m01** [comment]
`<Breadcrumbs>` is equivalent to `<Breadcrumbs.Root>` https://kobalte.netlify.app/docs/core/components/breadcrumbs#breadcrumbs-1
