### ISSUE TITLE
Improve performance of Select with a lot of items

### ISSUE THREAD

**Issue by jcmonnin** [kobaltedev/kobalte#71]
The performance of a `Select` with a lot of items (say 2000) is on the slow side.
It takes significant time for the first render and when opening it and trying to select an item, it's too slow to feel interactive.

Alternatively, virtual scroll could be provided.

There is a more detailed discussion on discord:
https://discord.com/channels/722131463138705510/1063803756388548709/1065933746034978856

**Comment by fabien-ml** [comment]
fixed in `v0.7.0`
