### ISSUE TITLE
Kobalte plugins (tailwind/vanilla-extract) don't target native selectors

### ISSUE THREAD

**Issue by p7gg** [kobaltedev/kobalte#91]
**Describe the bug**
Kobalte plugins (tailwind/vanilla-extract) don't target native selectors.
Is there any reason why the selectors for the plugins don't use the native selectors?

In both example `ui-hover`(tailwind) and `hover`(vanilla-extract) will only target the data attribute `data-hover`
```tsx
export function App() {
  return (
    <Button.Root class="ui-hover:bg-black ui-hover:text-white">
      Button
    </Button.Root>
  );
}
```
```tsx
const button = style([
  {
    background: "blue",
    padding: "2px 6px",
  },
  componentStateStyles({
    hover: {
      backgroundColor: "red",
    },
  }),
]);
```

**Expected behavior**
Often when prototyping I'll use the devtools to force states on some elements, and since it is only selecting the data attribute It just won't work - see img.
Ideally it should target both the native selector and the data-attr also? I really don't know whats the best alternative here

**Screenshots**
![image](https://user-images.githubusercontent.com/69444613/215284117-9c1d1240-f7e1-4336-9686-9022ef9b0ff6.png)

**Comment by riccardoperra** [comment]
Native selector works different and add that support can generate unwanted styles. For example, :hover styles can be applied also while the element has the disabled attribute, which this doesn't happen with data-hover.

Also, with vanilla-extract if you want you can apply directly the :hover selector natively.

```ts
const button = style([
  {
   ':hover': {
      backgroundColor: "red",
   }
  },
  componentStateStyles({
    hover: {
      backgroundColor: "red",
    },
  }),
]);
```

**Comment by p7gg** [comment]
> Native selector works different than the data-* states and adding that support can generate unwanted styles in my opinion. For example, :hover styles can be applied also while the element has the disabled attribute, which this doesn't happen with data-hover.
> 
> Also since you mentioned vanilla-extract, in that case you can apply directly the :hover selector natively.
> 
> ```ts
> const button = style([
>   {
>    ':hover': {
>       backgroundColor: "red",
>    }
>   },
>   componentStateStyles({
>     hover: {
>       backgroundColor: "red",
>     },
>   }),
> ]);
> ```

Understandable. Thank you for the explanation

**Comment by riccardoperra** [comment]
I don't know if this is a good like idea but at most we could add a configuration that further adds these styles.

```ts
  componentStateStyles({
    hover: {
      backgroundColor: "red",
    },
  }, { pseudoNative: true }),
```

will generate for example

```ts
.myButton:hover, myButton[data-hover]  {
  backgroundColor: "red",
}
```

**Comment by fabien-ml** [comment]
Is this issue still relevant given that there are no more `data-(hover|focus|active)` attributes in latest version of Kobalte ?
